### ISSUE TITLE
What does "JSON Support" mean?

### ISSUE THREAD

**Issue by yuttie** [blackbeam/rust-mysql-simple#117]
README.md says this crate offers JSON support, but it is not clear actually what support is provided.

**Comment by blackbeam** [comment]
Hi!

JSON is [supported by mysql since 5.7.8](https://dev.mysql.com/doc/refman/5.7/en/json.html). It is also a [new column type](https://github.com/blackbeam/rust-mysql-simple/blob/master/src/consts.rs#L114) in terms of mysql client-server protocol and it is supported since v9.0.0 of this crate.

Driver also provides basic support of serialization and deserialization (serde-based):

```rust
#[derive(Serialize)]
struct SerializableStruct {
    // ...
}

conn.prep_exec("INSERT INTO table (json_column) VALUES (?)",
               (Serialized(SerializableStruct),));
```

```rust
#[derive(Deserialize)]
struct DeserializableStruct {
    // ...
}
// ...
let (Deserialized(val),): (Deserialized<DeserializableStruct>,)
    = from_row(row_with_single_json_column);
```

**Comment by yuttie** [comment]
Ah, I got it.

I've just made a pull request #121, which simply add a link to the official documentation to README.md.
