### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by Julianlg752** [blackbeam/rust-mysql-simple#148]
Wecopied an pasted a code example somewhere, it used FromRow from_row, instead of from_row_opt, this meant the code pacnic!ed() in production.

It would be nice to have examples with from_row_opt instead of from_row to be the official examples, so that other programmers don't get bitten in the behind like we did.

**Comment by blackbeam** [comment]
Hi!
I've added a warning about `from_row` into an example, but please let me carify the purpose of `from_row` and `from_row_opt`:

- `from_row` will never panic if types you extracting from a row are in match with types actually present in a row. And, usually, you already know types in a row because you, as a programmer, have defined the database schema and wrote the query. So using `from_row_opt` here is useless and only complicates things.
- `from_row_opt` is the only option for you for cases where actual database schema are unknown and you just want to check if something like `SELECT * FROM some_row` matches with specific layout. Or maybe for cases where your query is so complex that you don't sure which columns it'll return)

⚠️ Note, that for MySql case it may not always be clear what your actual schema is. By this i mean implications of an active [sql mode][1] on your server. I.e. you may get NULL for a column explicitly definided as NOT NULL and other things like that.

[1] https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html
