### ISSUE TITLE
derive clone for Stmt

### ISSUE THREAD

**Issue by segler-alex** [blackbeam/rust-mysql-simple#189]
Hi, thank you for your work!

is it possible to derive Stmt struct from Clone?
i was thinking about preparing all my sql statements at program start and then just keeping/using them for all future database interaction. as soon as i start working with threads (for example for a web-api server) it gets needed to do a clone ( i did clone with pool, and there it works ).
could you add this or am i completely wrong in trying to do this?

thanks again

**Comment by blackbeam** [comment]
Hi.

Current library design won't allow you to clone `Stmt` because:
* statement in mysql only exists for connection it was prepared on
* mysql protocol is strictly sequential, i.e. you can't execute anything on the connection until previous action is fully executed (and result is fully consumed)

You can:
* put `Stmt` into `Arc<Murex<_>>` but such a statement, obviously, cannot be used in parallel;
* prepare required set of statements for every thread in your thread pool (if 8 of your threads wants to execute the same statement at the same moment in parallel then there is no other way to do this)

But actually I suggest you to keep using `Pool`, because prepared statements are cached in it.

**Comment by blackbeam** [comment]
Should be addressed in [v18.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v18.0.0).
