### ISSUE TITLE
SSL only available with old version (16.1.0)

### ISSUE THREAD

**Issue by biot023** [blackbeam/rust-mysql-simple#222]
Hi -- I'm developing apps that run against a MySQL server over SSL.
The latest version of the crate that supports this is 16.1.0, which is a number of releases behind the latest version (18.2.0).
Are there plans to re-enable OpenSSL support at any point or has connecting with it been deprecated?
Is there another way that people are connecting to SSL-secured MySQL instances that allows them to keep up with the latest version of the crate?
Thanks,
   Doug.

**Comment by blackbeam** [comment]
Hi.

I confused, because as far as I can see SSL support is available and tested in 18.0.2 (see [here][1], [here][2], [here][3] and [here][4]).

[1]: https://github.com/blackbeam/rust-mysql-simple/blob/master/src/lib.rs#L871
[2]: https://github.com/blackbeam/rust-mysql-simple/blob/master/src/conn/mod.rs#L1120
[3]: https://github.com/blackbeam/rust-mysql-simple/blob/master/azure-pipelines.yml#L37
[4]: https://dev.azure.com/aikorsky/mysql%20Rust/_build/results?buildId=31&view=logs&jobId=d9a650d5-9a56-5a67-2201-cbd6b5e3b462&j=d9a650d5-9a56-5a67-2201-cbd6b5e3b462&t=50c3c2ea-06a7-5cae-3e89-fcea01d048f1

**Comment by biot023** [comment]
This adds weight to my "I'm doing something wrong" theory.
In my cargo file I've specified SSL as a feature for MySQL and it installs 16.1.0.
When I try to upgrade the version it complains that 16.1.0 is the latest version that compiles with the SSL feature.
Does that mean that maybe I shouldn't be specifying SSL in my cargo file?

**Comment by blackbeam** [comment]
Oh, I see. SSL feature was removed since v0.17.0 (see [release notes](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v17.0.0)).
Actually this means, that SSL is always enabled since v17.0.0.

**Comment by biot023** [comment]
Which adds weight to my "I'm a muppet" theory.
Thanks @blackbeam -- I must've set up from an old version of the README or something, or copied-and-pasted from an older project.
I'll start getting that updated this weekend, something to pass the lockdown! :)
