### ISSUE TITLE
`start_transaction` when `db_name=None` panics

### ISSUE THREAD

**Issue by broccolihighkicks** [blackbeam/rust-mysql-simple#277]
I want to:
- A. Create database
- B. Create tables

All in one atomic unit/transaction, but:

`start_transaction` fails when the connection is created with `db_name=None` (and the database does not exist yet).

Is this possible, or do I need to first create the database on the connection and then open the transaction? 

## Error
```
 MySqlError { ERROR 1046 (3D000): No database selected }
```

This happens after:
```rust
let mut tx = c.start_transaction(TxOpts::default()).unwrap();
tx.query_drop("create tables ...").unwrap(); // <<< this line
```

## Fix

```rust

let mut tx = c.start_transaction(TxOpts::default()).unwrap();
tx.query_drop(format!("CREATE SCHEMA IF NOT EXISTS {}", x.create.db_name)).unwrap();
tx.query_drop(format!("USE {}", x.create.db_name)).unwrap();
tx.query_drop("create tables ...").unwrap();

// Sets default schema for the connection.
x.c.select_db(&x.create.db_name);
```

Is this the best way to do this?

**Comment by blackbeam** [comment]
Hi. Could you please share the panic message?

**Comment by blackbeam** [comment]
Regarding the fix: you can't create tables without selecting a database first. It does not actually matter if you are in transaction or not. Also note, that in MySql not all statements are possible to explicitly commit or rollback (please see [this article][1]), but things might change since 2017, so please also consult the docs for your database version.

[1]: https://hashrocket.com/blog/posts/mysql-has-transactions-sorta

**Comment by broccolihighkicks** [comment]
Ok thanks, my misunderstanding, you can delete this issue.
