### ISSUE TITLE
Pooled connections are dying after timeout

### ISSUE THREAD

**Issue by e-oz** [blackbeam/rust-mysql-simple#34]
I use AWS RDS, where default timeout connection is 8 hours. After 8 hours one of pooled connections is dying because of this limit and `ping()` can't detect it (or `reset()` doesn't work as expected with really dead connections).

**Comment by blackbeam** [comment]
Please try just published v1.2.1
`MyPool::get_conn` should deal with broken connections automatically.

**Comment by e-oz** [comment]
Thank you very much. Updated, will report tomorrow.

**Comment by e-oz** [comment]
No more 500's, thank you very much! :)

**Comment by kardeiz** [comment]
@blackbeam I'm having what appears to be the same issue, but with the current version `7.1.2`.

I'm using the pool in what I believe is a pretty standard way:

```rust
let server: hyper::server::Server = /* server */;
let pool = my::Pool::new(&*DB_URL).unwrap();
let handler = move |req, res| {
    let pool = pool.clone();
    // respond
};

server.handle(handler).unwrap();
```

This works fine for a while. After an extended period of time (more than a few hours), requests hang indefinitely. It's not an issue with Hyper (at least not directly), because requests that don't involve getting a pooled connection are successful. The pool itself seems to be intact because (in my simple setup) it is being cloned whether it is used or not, and some requests (as noted) are successful.

Sorry I can't provide more useful information. I'm not a MySQL expert, and the issue isn't providing any error details (or even any errors!).

**Comment by blackbeam** [comment]
I think it could be related to blackbeam/mysql_async#2
Which mysql/mariadb version do you use?

**Comment by blackbeam** [comment]
Just tried to reproduce this using latest mysql and mariadb but couldn't.
Behavior was emulated using `wait_timeout = 5` of mysql server (default is 8 hours).
According to inserted printnls pool connections was dropped by server (as desired), but pool successfully fixed them for following calls to `Pool::get_conn`, `Pool::prepare` and `Pool::prep_exec`.

Anyway. Your case doesn't look like timed out connection because it shouldn't hang indefinitely.

Need further investigation.

I am still interested in which server and version do you use.

**Comment by e-oz** [comment]
Works fine with 5.6 and 5.7, both on busy and idling servers (aws rds).

**Comment by kardeiz** [comment]
Thanks for the response!

The server MySQL version is `5.6.26`. `wait_timeout` is the default 8 hours (I don't have control over server configuration). Please let me know if there are any other variables that might be relevant.

(Also, I know that it is not your project, that it uses completely different logic, and that there are reasons to prefer your pool implementation, but the connection pooling of `r2d2-mysql` works fine for my case. Just in case that is relevant.)

**Comment by kardeiz** [comment]
Also, to clarify, this is not MariaDB: `version_comment` shows `MySQL Community Server (GPL)`

**Comment by blackbeam** [comment]
Pool uses a bit different routines for `get_conn` and `prep_exec`. Which one do you use inside of a handler?

And also for clarification, do mysql server located on the same host?

**Comment by kardeiz** [comment]
I'm using `prep_exec` for a SELECT query.

The MySQL server is on a separate server.

Thanks!

**Comment by blackbeam** [comment]
Ahh.. Still can't reproduce.

Could you please provide result of `SHOW VARIABLES;`?
And also what if you set `read_timeout` and `write_timeout`? Will it hang indefinitely?

**Comment by kardeiz** [comment]
Sorry for the long delay&mdash;I was on break.

I've pasted the output for `SHOW VARIABLES` at https://gist.github.com/kardeiz/5e9196a397a0e2603760db9ec46484d3.

I'm currently waiting to see whether setting read/write timeout on the client makes a difference.

**Comment by kardeiz** [comment]
Interesting&mdash;setting `read_timeout` and `write_timeout` to 5 seconds on `mysql::OptsBuilder` seems to have resolved the issue. However, there is a long delay (5-10 seconds) in processing a request if I wait more than 5 seconds between requests (I guess the client needs to completely reconnect?). Would the optimal value be just under 8 hours (the server's read/write timeout value)?

**Comment by blackbeam** [comment]
Could you please set new `tcp_keepalive_time_ms` option to something like one minute?

You need to switch to master branch to do this:

```toml
[dependencies.mysql]
git = "https://github.com/blackbeam/rust-mysql-simple.git"
```
