### ISSUE TITLE
error: could not compile `t6` (bin "t6") due to 1 previous error; 2 warnings emitted

### ISSUE THREAD

**Issue by zhujintao** [blackbeam/rust-mysql-simple#378]
= note: /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lssl: No such file or directory
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lcrypto: No such file or directory
          /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lz: No such file or directory
          collect2: error: ld returned 1 exit status

**Comment by blackbeam** [comment]
Hi.

I bet you are trying to build a statically linked binary. I was never actually tried that but first consider disabling the default set of crate features (`default-features = false`) and [enable only that you actually use](https://github.com/blackbeam/rust-mysql-simple?tab=readme-ov-file#crate-features). Secondly — if TLS support is necessary, then use `rustls-tls` instead of `native-tls`.

**Comment by zhujintao** [comment]
use env: ```RUSTFLAGS=-C target-feature=-crt-static```
