### ISSUE TITLE
why mut?

### ISSUE THREAD

**Issue by daogangtang** [blackbeam/rust-mysql-simple#39]
All the methods of MyPooledConn , need pass a mut self to, if only borrow, it'll be better to integrate between r2d2, and rustorm.

**Comment by blackbeam** [comment]
Hi! Sorry for late response.

All of `*Conn::*` methods takes `&mut self` because calls to, for instance `MyPooledConn::query`, while you still reading results from another call to `query` on this instanse of `MyPooledConn` will fail anyway and i decided to solve this at the compile time. The downside of this approach is that you can't prepare multiple statements on the same instance of `*Conn`, but it does not affects convenience match.
Library has a pool-level statements cache besides connection-level  cache and designed with assumption that it predominantly be used with calls to `MyPool::prep` and `MyPool::prep_exec`.

I think it's still possible to wrap library for `rustorm` integration. AFAIK it was already wrapped to some degree in ivanceras/rustorm#4.

Btw what's the point of r2d2? As far as i can see it just can't take pool-level statements cache to account.

**Comment by jscheel** [comment]
I'm a bit confused here too. So, if I need to make another query while iterating over the results of a query, I should get a new connection from the pool?

**Comment by blackbeam** [comment]
It's mysql protocol limitation. You must read previous result set from a connection socket to be able to perform another query on this connection.

`QueryResult` is lazy iterator. This means that it will not read result set from a socket until you iterate over it.

To emulate PHP-like "buffered" results on same connection you can act like PHP and collect results before actual processing. In pseudorust:
```rust
pool.get_conn().map(|mut conn| {
    let result_1 = conn.query("SELECT * FROM foo").unwrap().collect();
    let result_2 = conn.query("SELECT * FROM bar").unwrap().collect();
    for (row_from_set_1, row_from_set_2) in result_1.into_iter().zip(result_2.into_iter()) {
        // both results at the same time
    }
})
```

Or yes. You can get another connection from the pool. Ten of them already opened by default.

**Comment by jscheel** [comment]
Thanks for the detailed explanation!
