### ISSUE TITLE
Pool Performance

### ISSUE THREAD

**Issue by slde-flash** [blackbeam/rust-mysql-simple#53]
Hello,

i am using mysql-simple in a batch job, i've to run such a query around 50.000.000 times:

i use the default pool:
```rust
let pool = mysql::Pool::new(connection_string).unwrap();
```

and this code to run the query:
```rust
let mut result = match pool.prep_exec(
    &format!("SELECT x.x_id from {}.page where x.title = :title and x.foo = 0 LIMIT 1", database),
    params!{"title" => (Value::from(title))}
) {
    Ok(r) => r,
    Err(e) => { panic!("");}
};
```

i tryed to run this query in multiple threads (binary and the mysql server most time dont hit 30% cpu usage).
On my local pc the throughput don't increase (or change) if i run the same query using multiple threads. i also tryed to obfuscate  the query to prevent caching (using a SELECT ... and [random] = [random]).

the only real difference i can see by running multiple threads is that on osx kernel_thread starts to consume up to 100% cpu.

can you give me a hint how i can increase the load to the mysql server?

**Comment by blackbeam** [comment]
Thanks for report!

I am experiencing similar problem but i can't test possible fixes until wednesday.

Could you please test changes provided in #54 in case of single and multiple threads.
For this you need to clone `blackbeam-pool-performance` branch and point it's directory in your `Cargo.toml` like this:

```toml
[dependencies.mysql]
path = "/path/to/cloned/blackbeam-pool-performance/branch"
```

**Comment by blackbeam** [comment]
Well. #54 is definitely a bug, but it affects performance only for cases where number of threads is greater then `pool.min`.

My issue with batch job (around 30.000.000 small updates) was caused by unnecessary file IO on each iteration and was not related to a pool performance. Before i fixed this unnecessary file IO issue `top` shows me that mysql consumption is around 15% CPU and binary consumption is around 5% CPU. After fix - mysql around 250% CPU and binary around 150% CPU (on a server with 8 cores). So it looks like pool was not involved.

But pool **do have** overhead, so you will perform better if you take one connection per thread from a pool before entering into query loop.

I also have a few changes which reduces pool overhead for multi-threaded scenarios. I will publish them soon.

**Comment by blackbeam** [comment]
Please update to [v6.0.0](https://github.com/blackbeam/rust-mysql-simple/releases/tag/v6.0.0)
