### ISSUE TITLE
Reduce features list

### ISSUE THREAD

**Issue by DenisKolodin** [blackbeam/rust-mysql-simple#75]
I want to discuss current features state of the crate and future improvements.

@blackbeam You proposed to join **pipe** with **socket** feature there #71 . It's first possible and necessary strategy. But what about to remove features at all? I see we haven't strong reasons to keep and maintain features list.

What kind of simplification strategy we choose?

**Comment by blackbeam** [comment]
Yeah. I thought about.

#### socket pipe
Firstly maybe it's a good idea to remove socket and pipe features at all because 1. Socket connections is always faster than TCP. 2. Support does not requires third party libraries, i.e. included in OS.

#### sslI still think it is a good idea to leave ssl feature. 1. It's looks heavy. 2. It requires openssl on Unix and I'm not sure of it's availability on various of fancy Unix configurations.
But maybe it is a good idea to remove it from default feature set for reasons mentioned above.

#### uuid
Time and chrono support doesn't require any features so I think there is no reason to require feature to support uuid.

**Comment by DenisKolodin** [comment]
Cool! I like it. Do you have time to implement `socket+pipe` join? If not I can help you.

**Comment by blackbeam** [comment]
> Do you have time to implement `socket+pipe` join?

I do.
