### ISSUE TITLE
Drop rustc-serialize support

### ISSUE THREAD

**Issue by dtolnay** [blackbeam/rust-mysql-simple#94]
According to [Rust release milestone predictions](https://internals.rust-lang.org/t/rust-release-milestone-predictions/4591?u=dtolnay), rustc-serialize is scheduled to be deprecated in next month's beta release of Rust.

This would be a good time to let us know if there is any functionality you require from Serde before that happens.

**Comment by dtolnay** [comment]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by Thomspoon** [comment]
Wouldn't it make more sense to keep the functionality but point future users to serde as to not break anything what people already have implemented?

**Comment by dtolnay** [comment]
Why? If someone wants to use an outdated serialization library then they can also use an outdated version of this crate. They would just pull in an old version from crates.io.

**Comment by blackbeam** [comment]
Serde is used by default since v11.0.0 and rustc_serialze hidden behind `rustc-serialize` feature. This should works like pointing future users to serde. Update to v11 for old users should be as easy as adding `rustc-serialize` feature to `Cargo.toml`. Also anyone could use most up to date version of `mysql` with rustc_serialize if they wish to.

Since rustc_serialize support is trivial and mostly orthogonal to the library itself i can't see a reason to drop it completely.

I'm closing it for now. Feel free to reopen if i missed something.
